# PATH: calibration/biGauss_calibration.py

import numpy as np
from scipy.stats import norm
from scipy.interpolate import interp1d

from .logistic_regression import logistic_regression

# example input scores array:
#          s1,  s2, ...,  sn
# sys-1: [0.8, 1.0, ..., 0.9],
# sys-2: [1.5, 1.7, ..., 1.7],
# sys-3: [0.3, 1.4, ..., 0.8],
# ...
# sys-d: [0.6, 0.7, ..., 2.4].

class biGauss_calibration:
    """
    Bi-Gaussianized calibration module (logistic-regression variant, regularized version).

    Geoffrey Stewart Morrison (2024) and Phil Weber (2025) provided MATLAB and Python implementations
    of the logistic-regression variant of Bi-Gaussianized calibration described in Morrison (2024), available at:
    https://forensic-data-science.net/calibration-and-validation/

    We modified the original implementation to support logistic-regression fusion and used the Bi-Gaussianized step
    described by Morrison (2024) to transform the score toward a perfectly-calibrated bi-Gaussian distribution:
        X_ss ~ N(sigma2/2, sigma2)
        X_ds ~ N(-sigma2/2, sigma2)
    Note that when the task is single system calibration, the result should be equivalent to that of the original implementation.

    reference:
    Morrison, G. S. (2024).
    Bi-Gaussianized calibration of likelihood ratios.
    Law, Probability and Risk, 23(1), 1–34.
    https://doi.org/10.1093/lpr/mgae004

    Morrison, G. S., & Poh, N. (2018).
    Avoiding overstating the strength of forensic evidence: Shrunk likelihood ratios/Bayes factors.
    Science & Justice, 58(3), 200–218.
    https://doi.org/10.1016/j.scijus.2017.12.005
    """

    def __init__(self):
        self.LogReg = logistic_regression()

    def train(self,
              targets: np.ndarray,
              non_targets: np.ndarray,
              prior: float = 0.5,
              kappa: float = 0.01,
              df: int | None = None,
              max_iter: int = 50000) -> list:
        """
        Train a Bi-Gaussianized calibration model.

        :param targets: nt target scores for each of d systems, shape [d, nt].
        :param non_targets: nn non-target scores for each of d systems, shape [d, nn].
        :param prior: Prior probability of target, default as 0.5.
        :param kappa: Regularization factor of the logistic-regression,
                      <= 0.1 to improve numerical stability, >= 1 to introduce shrinkage.
        :param df: Pseudo degree of freedom of the logistic-regression,
                   n scores generated by a dataset of N sources, the 'df' should be N.
                   If no 'df' were specified, the default 'df' in this example would be n.
        :param max_iter: Max iteration number for Conjugate Gradient, default as 50000.

        :return: A list containing parameters for Bi-Gaussianized calibration.
        """

        targets = np.asarray(targets, dtype=float)
        non_targets = np.asarray(non_targets, dtype=float)

        d, nt = targets.shape
        d2, nn = non_targets.shape
        assert d == d2, "Warning: mismatch in system dimension"

        # Step-1: fit a regularized logistic-regression model
        fusion_w = self.LogReg.train(targets,
                                             non_targets,
                                             prior=prior,
                                             kappa=kappa,
                                             df=df,
                                             max_iter=max_iter)

        # Step-2: calibrate the calibration set to estimate the target Cllr
        quasi_ss = self.LogReg.apply(weights=fusion_w, scores=targets)
        quasi_ds = self.LogReg.apply(weights=fusion_w, scores=non_targets)

        punish_ss = np.logaddexp(0, -quasi_ss) / np.log(2)
        punish_ds = np.logaddexp(0, quasi_ds) / np.log(2)

        cllr_target = 0.5 * (np.mean(punish_ss) + np.mean(punish_ds))

        # Step-3: map the target Cllr to the target sigma2
        b = 17.665396790464737
        c = 0.009333834837656

        sigma2_target = -np.log((np.log(cllr_target) / b) + 1.0) / c
        sigma_target = np.sqrt(sigma2_target)
        half_sigma2 = sigma2_target / 2.0

        # Step-4: weighted empirical CDF of the uncalibrated scores
        w_ss = np.full(nt, 1.0 / ((nt + 1) * 2))
        w_ds = np.full(nn, 1.0 / ((nn + 1) * 2))

        quasi_all = np.concatenate([quasi_ds, quasi_ss])
        weights = np.concatenate([w_ds, w_ss])

        order = np.argsort(quasi_all)
        sorted_scores = quasi_all[order]
        sorted_weights = weights[order]

        uniq_scores, idx = np.unique(sorted_scores, return_inverse=True)
        summed_weights = np.zeros_like(uniq_scores)

        for i, w in zip(idx, sorted_weights):
            summed_weights[i] += w

        cdf_vals = np.cumsum(summed_weights)

        # values below/above calibration range are mapped to endpoint CDF values
        weighted_ecdf = interp1d(
            uniq_scores,
            cdf_vals,
            bounds_error=False,
            fill_value=(cdf_vals[0], cdf_vals[-1])
        )

        # Step-5 target Bi-Gaussian mixture CDF
        def bigmm_cdf(x):
            return 0.5 * norm.cdf(x, loc=-half_sigma2, scale=sigma_target) + \
                   0.5 * norm.cdf(x, loc=+half_sigma2, scale=sigma_target)

        return [fusion_w, cllr_target, sigma2_target, weighted_ecdf, bigmm_cdf]

    def apply(self,
              uncal_score: float | np.ndarray,
              model: list,
              grid_k: float = 4,
              grid_len: int = 10000) -> np.ndarray:
        """
        Calibrate scores by a pretrained Bi-Gaussianized calibration model.

        :param uncal_score: [d, n], uncalibrated score(s).
        :param model: BiGauss model returned by train_BiGauss().
        :param grid_k: Range (in multiples of sigma) for grid construction.
        :param grid_len: Number of grid points.

        :return calibrated_lnLR: [n, 1] array of the well-calibrated ln(LR).
        """

        fusion_w, _, sigma2_target, weighted_ecdf, bigmm_cdf = model

        X = np.asarray(uncal_score, dtype=float)

        if X.ndim == 0:
            X = X.reshape(1, 1)
        elif X.ndim == 1:
            X = X.reshape(1, -1)

        d = len(fusion_w) - 1
        if X.shape[0] != d:
            raise ValueError("Mismatch in system dimension (uncalibrated score).")

        # Step-1: pre-calibrate/fuse the score by LogReg
        quasi_uncal = self.LogReg.apply(weights=fusion_w, scores=X)
        quasi_uncal = np.asarray(quasi_uncal, dtype=float)

        # Step-2: search the ECDF value of the score in the calibration set
        qvals = weighted_ecdf(quasi_uncal)

        # Step-3: map the ECDF value to ln(LR) in the perfectly-calibrated Bi-Gaussian distribution
        half_sigma2 = sigma2_target / 2.0
        sigma_target = np.sqrt(sigma2_target)

        lnLR_max = half_sigma2 + grid_k * sigma_target
        lnLR_min = -lnLR_max

        grid = np.linspace(lnLR_min, lnLR_max, grid_len)
        target_cdf = bigmm_cdf(grid)

        # remove duplicated CDF values (required for interpolation)
        cdf_unique, idx = np.unique(target_cdf, return_index=True)
        grid_unique = grid[idx]

        inv_cdf = interp1d(
            cdf_unique,
            grid_unique,
            bounds_error=False,
            fill_value=(grid_unique[0], grid_unique[-1])
        )

        calibrated_lnLR = np.asarray(inv_cdf(qvals), dtype=float)
        return calibrated_lnLR.reshape(-1, 1)


