# PATH: calibration/logistic_regression.py

import numpy as np

# example input scores array:
#          s1,  s2, ...,  sn
# sys-1: [0.8, 1.0, ..., 0.9],
# sys-2: [1.5, 1.7, ..., 1.7],
# sys-3: [0.3, 1.4, ..., 0.8],
# ...
# sys-d: [0.6, 0.7, ..., 2.4].

class logistic_regression:
    """
    Regularized logistic-regression calibration method described by (Morrison & Poh, 2018).

    The technical description of this method can be fround in (Morrison & Poh, 2018).
    The original Python implementation by Phil Weber (2025) can be found in:
    https://forensic-data-science.net/calibration-and-validation/

    reference:
    Morrison, G. S., & Poh, N. (2018).
    Avoiding overstating the strength of forensic evidence: Shrunk likelihood ratios/Bayes factors.
    Science & Justice, 58(3), 200–218.
    https://doi.org/10.1016/j.scijus.2017.12.005
    """
    def __init__(self):
        pass

    def logit(self, p):
        """
        Compute the logit of a probability.

        :param p: probability value in the range (0, 1).

        :return: logit value, log(p / (1 - p)).
        """
        return np.log(p/(1-p))

    def cg_dir(self,
               old_dir: np.ndarray,
               grad: np.ndarray,
               old_grad: np.ndarray) -> np.ndarray:
        """
        Compute the updating conjugate-gradient search direction.

        :param old_dir: previous search direction, with shape [d+1, 1].
        :param grad: current gradient, with shape [d+1, 1].
        :param old_grad: previous gradient, with shape [d+1, 1].

        :return dir: new search direction, with shape [d+1, 1].
        """
        g = grad
        grad = grad.flatten()

        old_grad = old_grad.flatten()

        delta = grad - old_grad

        den = old_dir.T.dot(delta)
        if den == 0:
            dir = g * 0
        else:
            beta = np.dot(grad, delta) / den
            dir = g - beta * old_dir

        return dir

    def train(self,
              targets: np.ndarray,
              non_targets: np.ndarray,
              prior: float = 0.5,
              kappa: float = 0.0,
              df: int | None = None,
              max_iter: int = 50000) -> np.ndarray:
        """
        Fit a regularized logistic-regression model.

        :param targets: nt target scores for each of d systems, shape [d, nt].
        :param non_targets: nn non-target scores for each of d systems, shape [d, nn].
        :param prior: Prior probability of target, default as 0.5.
        :param kappa: Regularization factor,
                      <= 0.1 to improve numerical stability, >= 1 to introduce shrinkage,
                      default as 0 (no regularization).
        :param df: Pseudo degree of freedom,
                   n scores generated by a dataset of N sources, the 'df' should be N.
                   If no 'df' were specified, the default 'df' in this example would be n.
        :param max_iter: Max iteration number for the Conjugate Gradient, default as 50000.

        :return: d system weights + bias, shape [d+1, 1].
        """
        d, nt = targets.shape
        d2, nn = non_targets.shape
        assert d == d2, "Warning: mismatch in system dimension"

        ntnn = nt + nn
        prop = nt / ntnn

        if df is None:
            df = ntnn

        if kappa == 0:
            weights = np.hstack(((prior / prop) * np.ones(nt),
                                 ((1 - prior) / (1 - prop)) * np.ones(nn)))
            x = np.hstack((np.vstack((targets, np.ones(nt))),
                           -np.vstack((non_targets, np.ones(nn)))))
            offset = self.logit(prior) * np.hstack((np.ones(nt), -np.ones(nn)))
        else:
            # regularization
            weights_temp = np.hstack(((prior / prop) * np.ones(nt),
                                      ((1 - prior) / (1 - prop)) * np.ones(nn)))
            weight_flat_prior = kappa / (2 * df)
            weights_temp_flat_priors = weight_flat_prior * np.ones(ntnn * 2)
            weights = np.hstack((weights_temp, weights_temp_flat_priors))

            x_temp = np.hstack((np.vstack((targets, np.ones(nt))),
                                -np.vstack((non_targets, np.ones(nn)))))
            x = np.hstack((x_temp, x_temp, -x_temp))

            offset_temp = self.logit(prior) * np.hstack((np.ones(nt), -np.ones(nn)))
            offset = np.hstack((offset_temp, offset_temp, -offset_temp))

        w = np.zeros(x.shape[0])
        old_g = np.zeros_like(w)

        for iter in range(max_iter):
            old_w = w.copy()
            s1 = 1. / (1. + np.exp(w.T.dot(x) + offset))
            g = x.dot((s1 * weights).flatten().T)

            if iter == 0:
                u = g
            else:
                u = self.cg_dir(u, g, old_g)

            ug = u.T.dot(g)
            ux = u.T.dot(x)
            a = weights * s1 * (1 - s1)
            uhu = (ux ** 2).dot(a.T)

            w = w + (ug / uhu) * u
            old_g = g

            if np.max(np.abs(w - old_w)) < 1e-5:
                break

        else:
            print("Warning: not enough iterations")

        w = w.ravel()
        return w

    def apply(self,
              weights: np.ndarray,
              scores: np.ndarray | float) -> np.ndarray:
        """
        Linear logistic-regression calibration/fusion by pre-trained weights, adapted from (Brümmer, 2005).

        reference:
        Brümmer, N. (2005).
        FoCal Toolbox [MATLAB script].
        http://www.dsp.sun.ac.za/nbrummer/focal

        :param weights: d system weights + bias pre-trained by train_llr_fusion(), shape [d+1, 1].
        :param scores: n scores for each of d systems, shape [d, n].

        :return f: Calibrated or fused scores, shape [n,].
        """
        weights = np.asarray(weights).flatten()
        scores = np.asarray(scores)

        d, n = scores.shape

        if len(weights) != d + 1:
            print("Warning: mismatch in system dimension")
            return None

        augmented_scores = np.vstack([scores, np.ones((1, n))])

        f = weights @ augmented_scores
        return f


