# PATH: calibration/train_llr_fusion_regularized.py

import numpy as np

from .logit import logit
from .cg_dir import cg_dir

# example input scores array:
#          s1,  s2, ...,  sn
# sys-1: [0.8, 1.0, ..., 0.9],
# sys-2: [1.5, 1.7, ..., 1.7],
# sys-3: [0.3, 1.4, ..., 0.8],
# ...
# sys-d: [0.6, 0.7, ..., 2.4].

def train_llr_fusion_regularized(targets: np.ndarray,
                                 non_targets: np.ndarray,
                                 prior: float = 0.5,
                                 kappa: float = 0.0,
                                 df: int | None = None,
                                 max_iter: int = 50000) -> np.ndarray:
    """
    Calibration weight estimation by Logistic Regression (regularized version).

    The technical description of this method can be fround in (Morrison & Poh, 2018). The original Python implementation
    by Phil Weber (2025) can be found in:
    https://forensic-data-science.net/calibration-and-validation/

    Here we modified the original implementation

    reference:
    Morrison, G. S., & Poh, N. (2018).
    Avoiding overstating the strength of forensic evidence: Shrunk likelihood ratios/Bayes factors.
    Science & Justice, 58(3), 200–218.
    https://doi.org/10.1016/j.scijus.2017.12.005

    :param targets: nt target scores for each of d systems, shape [d, nt].
    :param non_targets: nn non-target scores for each of d systems, shape [d, nn].
    :param prior: Prior probability of target, default as 0.5.
    :param kappa: Regularization factor,
                  <= 0.1 to improve numerical stability, >= 1 to introduce shrinkage,
                  default as 0 (no regularization).
    :param df: Pseudo degree of freedom,
               n scores generated by a dataset of N sources, the 'df' should be N.
               If no 'df' were specified, the default 'df' in this example would be n.
    :param max_iter: Max iteration number for Conjugate Gradient, default as 50000.

    :return: d system weights + bias, shape [d+1, 1].
    """

    d, nt = targets.shape
    d2, nn = non_targets.shape
    assert d == d2, "Warning: mismatch in system dimension"

    ntnn = nt + nn
    prop = nt / ntnn

    if df is None:
        df = ntnn

    if kappa == 0:
        weights = np.hstack(((prior/prop) * np.ones(nt),
                             ((1-prior)/(1-prop)) * np.ones(nn)))
        x = np.hstack((np.vstack((targets, np.ones(nt))),
                       -np.vstack((non_targets, np.ones(nn)))))
        offset = logit(prior) * np.hstack((np.ones(nt), -np.ones(nn)))
    else:
        # regularization
        weights_temp = np.hstack(((prior/prop) * np.ones(nt),
                                  ((1-prior)/(1-prop)) * np.ones(nn)))
        weight_flat_prior = kappa / (2 * df)
        weights_temp_flat_priors = weight_flat_prior * np.ones(ntnn * 2)
        weights = np.hstack((weights_temp, weights_temp_flat_priors))

        x_temp = np.hstack((np.vstack((targets, np.ones(nt))),
                            -np.vstack((non_targets, np.ones(nn)))))
        x = np.hstack((x_temp, x_temp, -x_temp))

        offset_temp = logit(prior) * np.hstack((np.ones(nt), -np.ones(nn)))
        offset = np.hstack((offset_temp, offset_temp, -offset_temp))

    w = np.zeros(x.shape[0])
    old_g = np.zeros_like(w)

    for iter in range(max_iter):
        old_w = w.copy()
        s1 = 1. / (1. + np.exp(w.T.dot(x) + offset))
        g = x.dot((s1 * weights).flatten().T)

        if iter == 0:
            u = g
        else:
            u = cg_dir(u, g, old_g)

        ug = u.T.dot(g)
        ux = u.T.dot(x)
        a = weights * s1 * (1 - s1)
        uhu = (ux**2).dot(a.T)

        w = w + (ug / uhu) * u
        old_g = g

        if np.max(np.abs(w - old_w)) < 1e-5:
            break

    else:
        print("Warning: not enough iterations")

    w = w.ravel()
    return w
