# calibration/train_BiGauss_regularized.py

import numpy as np
from scipy.stats import norm
from scipy.interpolate import interp1d

from .train_llr_fusion_regularized import train_llr_fusion_regularized
from .lin_fusion import lin_fusion

# example input scores array:
#          s1,  s2, ...,  sn
# sys-1: [0.8, 1.0, ..., 0.9],
# sys-2: [1.5, 1.7, ..., 1.7],
# sys-3: [0.3, 1.4, ..., 0.8],
# ...
# sys-d: [0.6, 0.7, ..., 2.4].

def train_BiGauss_regularized(targets: np.ndarray,
                              non_targets:  np.ndarray,
                              prior: float = 0.5,
                              kappa: float = 0.01,
                              df: int | None = None,
                              max_iter: int = 50000) -> list:
    """
    Bi-Gaussianized calibration model training module (LogReg variant, regularized version).

    Geoffrey Stewart Morrison (2024) and Phil Weber (2025) provided MATLAB and Python implementations
    of the logistic-regression variant of Bi-Gaussianized calibration described in Morrison (2024), available at:
    https://forensic-data-science.net/calibration-and-validation/

    We modified the original implementation to support logistic-regression fusion and used the Bi-Gaussianized step
    described by Morrison (2024) to transform the score toward a perfectly-calibrated bi-Gaussian distribution.
    Note that when the task is calibration of a single system, the result should be equivalent to that of the original implementation.

    reference:
    Morrison, G. S. (2024).
    Bi-Gaussianized calibration of likelihood ratios.
    Law, Probability and Risk, 23(1), 1–34.
    https://doi.org/10.1093/lpr/mgae004

    Morrison, G. S., & Poh, N. (2018).
    Avoiding overstating the strength of forensic evidence: Shrunk likelihood ratios/Bayes factors.
    Science & Justice, 58(3), 200–218.
    https://doi.org/10.1016/j.scijus.2017.12.005

    :param targets: nt target scores for each of d systems, shape [d, nt].
    :param non_targets: nn non-target scores for each of d systems, shape [d, nn].
    :param prior: Prior probability of target, default as 0.5.
    :param kappa: Regularization factor,
                  <= 0.1 to improve numerical stability, >= 1 to introduce shrinkage.
    :param df: Pseudo degree of freedom,
               n scores generated by a dataset of N sources, the 'df' should be N.
               If no 'df' were specified, the default 'df' in this example would be n.
    :param max_iter: Max iteration number for Conjugate Gradient, default as 50000.

    :return: A list containing parameters for Bi-Gaussianized calibration.
    """

    targets = np.asarray(targets, dtype=float)
    non_targets = np.asarray(non_targets, dtype=float)

    d, nt = targets.shape
    d2, nn = non_targets.shape
    assert d == d2, "Warning: mismatch in system dimension"

    # Step-1: fit a regularized logistic-regression model
    fusion_w = train_llr_fusion_regularized(targets, non_targets,
                                            prior=prior,
                                            kappa=kappa,
                                            df=df,
                                            max_iter=max_iter)

    # Step-2: calibrate the calibration set to estimate target Cllr
    quasi_ss = lin_fusion(weights=fusion_w, scores=targets)
    quasi_ds = lin_fusion(weights=fusion_w, scores=non_targets)

    punish_ss = np.logaddexp(0, -quasi_ss) / np.log(2)
    punish_ds = np.logaddexp(0, quasi_ds) / np.log(2)

    cllr_target = 0.5 * (np.mean(punish_ss) + np.mean(punish_ds))

    # Step-3: map target Cllr to target sigma
    b = 17.665396790464737
    c =  0.009333834837656

    sigma2_target = -np.log((np.log(cllr_target) / b) + 1.0) / c
    sigma_target = np.sqrt(sigma2_target)
    half_sigma2 = sigma2_target / 2.0

    # Step-4: weighted empirical CDF of uncalibrated scores
    w_ss = np.full(nt, 1.0 / ((nt + 1) * 2))
    w_ds = np.full(nn, 1.0 / ((nn + 1) * 2))

    quasi_all = np.concatenate([quasi_ds, quasi_ss])
    weights = np.concatenate([w_ds, w_ss])

    order = np.argsort(quasi_all)
    sorted_scores = quasi_all[order]
    sorted_weights = weights[order]

    uniq_scores, idx = np.unique(sorted_scores, return_inverse=True)
    summed_weights = np.zeros_like(uniq_scores)

    for i, w in zip(idx, sorted_weights):
        summed_weights[i] += w

    cdf_vals = np.cumsum(summed_weights)

    weighted_ecdf = interp1d(
        uniq_scores,
        cdf_vals,
        bounds_error=False,
        fill_value=(0.0, 1.0)
    )

    # Step-5 target Bi-Gaussian mixture CDF
    def bigmm_cdf(x):
        return 0.5 * norm.cdf(x, loc=-half_sigma2, scale=sigma_target) + \
               0.5 * norm.cdf(x, loc=+half_sigma2, scale=sigma_target)

    return [
        fusion_w,
        cllr_target,
        sigma2_target,
        weighted_ecdf,
        bigmm_cdf
    ]

